### ISSUE TITLE
Implement updates

### ISSUE THREAD

**Issue by Bouncey** [Bouncey/freeCodeCamp-Elasticsearch#3]
Implement webhooks to run an upsert on that particular data set when triggered.

- [x] guides webhook
- [x] challenges webhook
- [ ] youtube webhook

**Comment by systimotic** [comment]
@Bouncey What's the scope of this issue?

**Comment by Bouncey** [comment]
Oh yes, I opened this issue just to remind myself.

Implement webhooks to run an upsert on that particular data set when triggered.

- [x] guides webhook
- [x] challenges webhook
- [ ] youtube webhook
