### ISSUE TITLE
Secure webhooks

### ISSUE THREAD

**Issue by systimotic** [Bouncey/freeCodeCamp-Elasticsearch#38]
Anybody can currently trigger the webhooks to do a rebuild. This could potentially allow somebody to bring down the server without too much effort, given that it seems the update is still a fairly expensive action.

A resource on securing the webhooks: https://developer.github.com/webhooks/securing/

**Comment by Bouncey** [comment]
:lock: :+1:

**Comment by systimotic** [comment]
I think this was fixed through https://github.com/freeCodeCamp/search/commit/fd30c29490

**Comment by Bouncey** [comment]
correct
