### ISSUE TITLE
No results when query contains space

### ISSUE THREAD

**Issue by systimotic** [Bouncey/freeCodeCamp-Elasticsearch#66]
While QA'ing https://github.com/freeCodeCamp/guides/pull/7954, I noticed that whenever there was a space in my search query I always got an empty array back.

I can also reproduce this on the live https://guide.freecodecamp.org

@Bouncey

**Comment by Bouncey** [comment]
This repo is being archived, further development will  continue in the [freecodecamp/search-mono-repo](https://github.com/freeCodeCamp/search-mono-repo)

Many thanks
